### ISSUE TITLE
UAVCAN cannot be connected

### ISSUE THREAD

**Issue by ptss37** [NXPHoverGames/RDDRONE-BMS772#1]
**Describe the bug**
For testing UAVCAN Task of BMS3.6, I connected the BMS with the PX4, enabled UAVCAN in the QGroundControl and entered command 'uavcan status' to the MAVLink Console. But the BMS node was not checked. What more can I check?

I found that it didn't get out of the loop to set the node_id when node_id was unset in the 'uavcan_task_initialize()'. As I checked, the node_id was still unset. Please refer to the screenshot I attached.

**Environment**
OS : Ubuntu 18.04.5
PX4 : v1.11.3
BMS : BMS3.6

![스크린샷, 2021-02-09 20-11-52](https://user-images.githubusercontent.com/30312096/107356884-b8dde580-6b14-11eb-9bbf-a4feee9e55d3.png)
![스크린샷, 2021-02-09 21-02-00](https://user-images.githubusercontent.com/30312096/107361051-1cb6dd00-6b1a-11eb-9cd3-e6af1d06c285.png)
![20210209_211419](https://user-images.githubusercontent.com/30312096/107362366-ff830e00-6b1b-11eb-926d-645294147589.jpg)

**Comment by igalloway** [comment]
Thank you for your issue report.

UAVCANv1 specification is not completely settled with regards to device profiles for Drones and Rovers. We have in the meanwhile put the basic support in place for developers, and are also participating in this development effort ourselves.

So the short answer is that UAVCANv1 support is still a work in progress, but basic in BMS-772 and PX4 are in place as can be seen here:
https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/uavcan_v1

PX4 opensource development community hosts weekly calls to discuss, and progress is starting to accelerate.
We will plan to post an update here when PX4 FMU code properly supports the BMS with UAVCANv1
