### ISSUE TITLE
SMBus crashes after a while

### ISSUE THREAD

**Issue by B00M3RSIX** [NXPHoverGames/RDDRONE-BMS772#10]
Hi there,

During the last days I'm trying to use the SMBus implementation to retrieve values from the RDDRONE-BMS772 (FW bms5.0-10.1).
Initally it works like a charm but then after a random time the communicaiton stops until I reboot the BMS from CLI or power-cycle the BMS. Restarting the master didn't help in any case when the communicaiton has stopped.
First I used a simple pyhton script on NVIDIA Xavier NX dev-kit using "smbus2 0.4.1" library.
Then I also tried a teensy 4.0 with serveral diffrent libraries to establish the communicaiton (as i2c master).
Usually i did run the speed at 100kbit/s but also tried diffrent ones. I also tried different Pullups-setups with no effective result. During tests the BMS and the master were the only devices on the bus.
At the NX the communicaiton works 20+ minutes if I read voltage and current at a 1Hz rate (I think it was ~1h in max) - if I read faster it likely it crahses faster - on teensy just in main loop with a couple of ms delay its less then one minute.
As I tried with different devices and different libraries on the master I tend to think the problem is on the BMS side. But I'm not familiar with the BMS and nuttx (especially on those driver levels) so I need some help getting started for debuging here.
To check if the problem is not on my master implementation... do you have a known reliable setup/library for python implementation on raspberry pi / Xavier NX or a sketch/plattform.io-project for arduino / teensy which I can test?

Thx in advance

**Comment by cisvanmierlo** [comment]
Hi @B00M3RSIX,

Thank you for pointing out this potential issue.
We will investigate this in more detail and get back to you as soon as we can.
Please allow us some time to replicate the setup you have described.
We will debug this on our site and will update you on what we discover.

Kind regards,

Cis van Mierlo

**Comment by cisvanmierlo** [comment]
Hi @B00M3RSIX,

We have tried to reproduce the issue on our side.
While using the 5.0 binary provided on https://github.com/NXPHoverGames/RDDRONE-BMS772/tree/main/Binary.
We have not yet been able to reproduce this issue on our side.

We use the packprobe program to read the bms data, which can be found here:
PackProbe: https://github.com/PowerCartel/PackProbe
Which requires SoftI2CMaster library: https://www.arduino.cc/reference/en/libraries/softi2cmaster/

Could you perhaps elaborate more on the setup used?
For example, do you have a load connected to the BMS?
How much current does the load draw?
Could you share the set parameters via the "bms get all" comand?
Does the CLI state something before this happens?

Chapter 7.5 of the release notes describes the supported smart battery data messages.
See the following link for the release notes of 5.0:
https://github.com/NXPHoverGames/RDDRONE-BMS772/blob/main/BMS772_releaseNotes_5.0.pdf

Kind regards,

Cis van Mierlo

**Comment by B00M3RSIX** [comment]
Hi @cisvanmierlo,

sorry for the late responce - finally I could find some time to try out your mentioned setup. So far it seems to work flawless - currently I'm at 7 hours continuous monitoring without any issues yet. I will keep your setup running for some more time until I close the issue.

As you asked:
BMS-parameters are stock beside to enable smbus, and putting in the battery data (3s Lipo 5000mAh) and its the fw you stated out. Only a small load (100mA) is connected while the test (just enough not to go to sleep mode). So far I only discharged with BMS - charging was done with a Lipo charger (without BMS).
Adapter from the dronekit (Segger J-Link Mini debugger + FTDI for CLI) was connected all the time at J19.
The BMS was modified to have the diode on from D35 to D34 like you mentioned [here].(https://github.com/NXPHoverGames/RDDRONE-BMS772/issues/9#issuecomment-1035936629)

Not shure what's the problem with my setup though... If i find time next weekend I will dig into it more...
With the Jetson Xavier NX and the smbus2 0.4.1 library I'll see with `dmesg | grep i2c`:

```
[ 4376.868216] tegra-i2c 31e0000.i2c: pio timed out addr: 0x8 tlen:28 rlen:4
[ 4376.868418] tegra-i2c 31e0000.i2c: --- register dump for debugging ----
[ 4376.868537] tegra-i2c 31e0000.i2c: I2C_CNFG - 0x22c00
[ 4376.868628] tegra-i2c 31e0000.i2c: I2C_PACKET_TRANSFER_STATUS - 0x10001
[ 4376.868742] tegra-i2c 31e0000.i2c: I2C_FIFO_CONTROL - 0x0
[ 4376.868861] tegra-i2c 31e0000.i2c: I2C_FIFO_STATUS - 0x800080
[ 4376.868961] tegra-i2c 31e0000.i2c: I2C_MST_FIFO_CONTROL - 0x70000
[ 4376.869069] tegra-i2c 31e0000.i2c: I2C_MST_FIFO_STATUS - 0x7c0000
[ 4376.869175] tegra-i2c 31e0000.i2c: I2C_MST_PACKET_TRANSFER_CNT - 0x0
[ 4376.869308] tegra-i2c 31e0000.i2c: I2C_INT_MASK - 0x7d
[ 4376.869403] tegra-i2c 31e0000.i2c: I2C_INT_STATUS - 0x2
[ 4376.869497] tegra-i2c 31e0000.i2c: i2c transfer timed out addr: 0x8
[ 4379.531255] tegra-i2c 31e0000.i2c: no acknowledge from address 0x8
```

Thanks for you help

**Comment by B00M3RSIX** [comment]
Hi @cisvanmierlo,
I finally could make out the issue... the problem was a to high colckspeed on SCL. I didn't know that SMBUS speed range is not at the typical I2C-Speed from 100kHz to 400kHz. The packprobe sketch you mentioned gave me the hint where it set the speed to "I2C_SLOWMODE" which sets the speed to 25kHz.
The default 100kHz seemed to be just on the edge why it chrashed at such random times. After changing the speed on the Jetson Xavier It works there, too. 
Sometimes you only need a push in the right direction ;-)
Thanks for your effort.
