### ISSUE TITLE
when built to create a binary for the firmware error reporting a missing libcanard library.

### ISSUE THREAD

**Issue by suvasis** [NXPHoverGames/RDDRONE-BMS772#11]
[Setup_log_Build_error_log.txt](https://github.com/NXPHoverGames/RDDRONE-BMS772/files/11009228/Setup_log_Build_error_log.txt)

I purchased a RDDRONE-BMS772 dev board recently. 

As per the build instruction here,

I have installed Windows Subsystem for Linux (Ubuntu) and followed the instructions on Git to setup the toolchain and build the firmware. Setup is fine, however when built to create a binary for the firmware (both Normal and Debug configuration) results in an error reporting a missing libcanard library. The setup and build log is attached for your reference. Shall look for solution on how to resolve this.

Can you pls point to missing libcanard library?
Thanks
suvasis

**Comment by igalloway** [comment]
We'll have a look at this and get back to you.

On Mar 18, 2023 12:58 PM, suvasis ***@***.***> wrote:

Caution: EXT Email

Setup_log_Build_error_log.txt<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNXPHoverGames%2FRDDRONE-BMS772%2Ffiles%2F11009228%2FSetup_log_Build_error_log.txt&data=05%7C01%7Ciain.galloway%40nxp.com%7C3d84a88f8abe4f68a92f08db27da63db%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C638147591150532923%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B8hQhKx5rLWCEjhLbHvaWvlfogHgFxgT1%2BFfxvHjWjw%3D&reserved=0>

I purchased a RDDRONE-BMS772 dev board recently.

As per the build instruction here,

I have installed Windows Subsystem for Linux (Ubuntu) and followed the instructions on Git to setup the toolchain and build the firmware. Setup is fine, however when built to create a binary for the firmware (both Normal and Debug configuration) results in an error reporting a missing libcanard library. The setup and build log is attached for your reference. Shall look for solution on how to resolve this.

Can you pls point to missing libcanard library?
Thanks
suvasis

**Comment by cisvanmierlo** [comment]
Hi @suvasis,

Could you maybe check if you have the unzip application on your WSL machine?
It looks like the MakeFile can not find the path for unzip.

Otherwise I can see that you fetch the libcanard library and saved it in: '/root/drones/apps/canutils/libcanardv1'.
Maybe check the content of this folder.

Kind regards,

Cis van Mierlo

**Comment by suvasis** [comment]
i was able to create the binary. pls close the issue.

**Comment by igalloway** [comment]
Thanks for using GitHub to report the issue.
