### ISSUE TITLE
Error while uploading binary

### ISSUE THREAD

**Issue by feemi** [NXPHoverGames/RDDRONE-BMS772#3]
**Describe the bug**
We could not manage to flash nuttx firmware to bms772 kit. We tried zubax dronecode prober via SWD interface

Steps
```
arm-none-eabi-gdb nuttx
tar ext /dev/ttyACMX
mon swdp_scan
(gdb) mon swdp_scan
Target voltage: 3.2V
Available Targets:
No. Att Driver
 1      ARM Cortex-M
(gdb) mon swdp_scan
Target voltage: 3.2V
Available Targets:
No. Att Driver
 1      Kinetis Recovery (MDM-AP)
(gdb) mon swdp_scan
Target voltage: 3.2V
Available Targets:
No. Att Driver
 1      ARM Cortex-M
(gdb) mon swdp_scan
Target voltage: 3.2V
Available Targets:
No. Att Driver
 1      ARM Cortex-M
(gdb) attach 1 
Attaching to Remote target
Attaching to Remote target failed
```

In one attempt it succeded to attach but loading elf file failed like below

```
Attaching to program: /home/fehmi/github/bms/nuttx/nuttx, Remote target
warning: while parsing target memory map (at line 1): Required element <memory> is missing
0xfffffffe in ?? ()
(gdb) load
Loading section .vectors, size 0x28c lma 0x0
Load failed
```

**Comment by igalloway** [comment]
All our testing is done with Segger debuggers - and specifically the one used in HoverGames.
https://nxp.gitbook.io/rddrone-bms772/user-guide/getting-started-with-the-rddrone-bms772/flashing-firmware-to-the-rddrone-bms772

I suppose you do not have this hardware?

**Comment by feemi** [comment]
We have bms772 kit
https://www.nxp.com/design/designs/rddrone-bms772-smart-battery-management-for-mobile-robotics:RDDRONE-BMS772 

And debugger we use is based on blackmagic
https://shop.zubax.com/products/dronecode-probe-v2-2-jtag-swd-adapter-usb-uart-adapter-with-dcd-m-cable

**Comment by igalloway** [comment]
You mentioned in slack that you tried another device programmed as a JLINK. Could you post the output your results here?
Are you able to use JLINK.exe (Jlink commander) and see the same steps as shown in our gitbook?
https://nxp.gitbook.io/nxpmobilerobotics/flashing-guide/flashing-hovergames-boards
![image](https://user-images.githubusercontent.com/10509054/109344322-efba3800-7844-11eb-9282-dc18ac7878b3.png)

Regarding the Zubax blackmagic - i'll talk with Pavel to see if this is something he can support.

**Comment by feemi** [comment]
Thanks @igalloway. 
I ve tried with stlink2 with jlink firmware. it seems to identify device with jlinkexe but i think it only allows to work with stm devices.

**Comment by igalloway** [comment]
Ok. That's probably a restriction on the ST-Link.
Let me think of some options

**Comment by greg-draganfly** [comment]
I ran into exactly the same problem.  Would like know if a solution has been figured out.

How can I configure the build system to produce an elf file?  This might help with the flashing and will definitely help with debugging.

**Comment by igalloway** [comment]
Do you have a segger jlink or Jlink-EDU you could use? We provide one with
the HoverGames drone kit. But not the BMS.
Any open debugger should work. (ST-LInk is clearly locked to their parts
only)
