### ISSUE TITLE
Setup for Pixhawk 4

### ISSUE THREAD

**Issue by divyanshu1234** [NXPHoverGames/RDDRONE-BMS772#4]
I have been trying to interface the RDDRONE-BMS772 with a Pixhawk 4 running px4_fmu-v5_default. I have connected both the devices using the `can1` port, and when I run `uavcan status` on `nsh` I can see that some data is being transferred through `can1` before the BMS becomes inactive.

I am not sure how to proceed from here. First of all, will this work with px4_fmu-v5_default or will I have to install some other build?

**Comment by divyanshu1234** [comment]
Is work still being done on this project?

**Comment by PetervdPerk-NXP** [comment]
Hi,

The RDDRONE-BMS772 only implements an early version UAVCANv1 with DS-015.
Your pixhawk 4 is probably running UAVCANv0 wich will not work.
There's an experimental UAVCANv1 you could use see https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v5/uavcanv1.cmake

**Comment by suvasis** [comment]
can pls resend the link  https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v5/uavcanv1.cmake, this is 404

**Comment by cisvanmierlo** [comment]
Hi @suvasis ,
I think this is the new link: https://github.com/PX4/PX4-Autopilot/blob/main/boards/px4/fmu-v5/cyphal.px4board
