### ISSUE TITLE
Cannot open CLI via JTAG port (J2)

### ISSUE THREAD

**Issue by Juanito970** [NXPHoverGames/RDDRONE-BMS772#5]
Flashing the BMS using nuttx.bin does not allow CLI connection via JTAG using a Segger mini EDU Debugger, ¿Is this expected? As far as I can see in the hardware block diagram the ports SWD and DCZ are connected.
![image](https://user-images.githubusercontent.com/36969954/118206807-e2b2eb00-b428-11eb-94bb-efc510244f15.png)

**Comment by cisvanmierlo** [comment]
Hi @Juanito970, the debug port of the MCU is connected to the DCD-LZ debug connector, if you use this connector, you need to use an FTDI cable to access the CLI. 

On the SWD DEBUG pins, you can not get the CLI, as this comes from the LPUART1 of the MCU.
