### ISSUE TITLE
display in 5.0

### ISSUE THREAD

**Issue by B00M3RSIX** [NXPHoverGames/RDDRONE-BMS772#9]
Should the display show anything with 5.0 if I flash the binary out of the repo?
It stays black in any case. For now no load was connected yet
Init in CLI doesn't show problems.
I also verified the display is working with an arduino.

**Comment by cisvanmierlo** [comment]
Hi @B00M3RSIX, 
For now, the display support is only added for 3.3V and not 5V.
The 5V is disabled during startup, which results in the NuttX driver not able to initialize the display.

Could you make sure D34 is placed and not D35?
This should make sure that 3.3V is supplied to pin 2 of J23.

**Comment by B00M3RSIX** [comment]
Hi @cisvanmierlo,
D35 is placed.
Kind of strange to premount a display to the board and the hardware layout isn't suitable. But I'm glad that it boots up without errors (compared to prev. verision).
Anyway thx for the answer.
